name: ✨Automated Build✨

on: 
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  buildWindows:
    name: 💻Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Unity-Auto-Build-Sample~/
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: StandaloneWindows64

      # Check for dirty branch
      - name: Check diff if dirty-branch error caused
        if: failure()
        run: |
          git diff --name-only > modified_files.txt
          echo "List of modified files:"
          cat modified_files.txt
          while read -r line; do
            echo "Changes in $line:"
            git diff "$line"
          done < modified_files.txt

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: build-StandaloneWindows64
          path: build/StandaloneWindows64
          
  buildMacOS:
    name: 💻macOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Unity-Auto-Build-Sample~/
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: StandaloneOSX

      # Check for dirty branch
      - name: Check diff if dirty-branch error caused
        if: failure()
        run: |
          git diff --name-only > modified_files.txt
          echo "List of modified files:"
          cat modified_files.txt
          while read -r line; do
            echo "Changes in $line:"
            git diff "$line"
          done < modified_files.txt

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: build-StandaloneOSX
          path: build/StandaloneOSX
