name: Temporary Action for manual activation

on:
  workflow_dispatch: {}
    
jobs:
  activation:
    name: Manual activation
    runs-on: ubuntu-latest
    
    steps:
      # activation
      - name: Activation project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
